/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Props } from "./components/wc-button/type";
export namespace Components {
    interface SampleContainer {
        /**
          * click event
         */
        "handleClicked": () => Promise<void>;
    }
    interface WcButton {
        /**
          * fit button width to its parent width
         */
        "block": Props['block'];
        /**
          * button disabled
         */
        "disabled": Props['disabled'];
        /**
          * html button type
         */
        "htmlType": Props['htmlType'];
        /**
          * show loading icon
         */
        "loading": Props['loading'];
        /**
          * size of button
         */
        "size": Props['size'];
        /**
          * theme of button
         */
        "theme": Props['theme'];
    }
}
declare global {
    interface HTMLSampleContainerElement extends Components.SampleContainer, HTMLStencilElement {
    }
    var HTMLSampleContainerElement: {
        prototype: HTMLSampleContainerElement;
        new (): HTMLSampleContainerElement;
    };
    interface HTMLWcButtonElement extends Components.WcButton, HTMLStencilElement {
    }
    var HTMLWcButtonElement: {
        prototype: HTMLWcButtonElement;
        new (): HTMLWcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "sample-container": HTMLSampleContainerElement;
        "wc-button": HTMLWcButtonElement;
    }
}
declare namespace LocalJSX {
    interface SampleContainer {
    }
    interface WcButton {
        /**
          * fit button width to its parent width
         */
        "block"?: Props['block'];
        /**
          * button disabled
         */
        "disabled"?: Props['disabled'];
        /**
          * html button type
         */
        "htmlType"?: Props['htmlType'];
        /**
          * show loading icon
         */
        "loading"?: Props['loading'];
        /**
          * click event emit
         */
        "onClicked"?: (event: CustomEvent<any>) => void;
        /**
          * size of button
         */
        "size"?: Props['size'];
        /**
          * theme of button
         */
        "theme"?: Props['theme'];
    }
    interface IntrinsicElements {
        "sample-container": SampleContainer;
        "wc-button": WcButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sample-container": LocalJSX.SampleContainer & JSXBase.HTMLAttributes<HTMLSampleContainerElement>;
            "wc-button": LocalJSX.WcButton & JSXBase.HTMLAttributes<HTMLWcButtonElement>;
        }
    }
}
